07_django/04_django_urls/articles/urls.py
from django.urls import path
# 명시적 상대경로 (django 권장사항)
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('dinner/', views.dinner, name='dinner'),
    path('search/', views.search, name='search'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('<int:num>/', views.detail, name='detail'),
    path('hello/<str:name>/', views.greeting, name='greeting'),
]

07_django/04_django_urls/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
# urls.py 입장에서는 
# articles라는 패키지에서
# views라는 모듈을 가져오는 것
# from articles import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

07_django/04_django_urls/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
]

07_django/04_django_urls/pages/models.py
from django.db import models

# Create your models here.

07_django/04_django_urls/articles/views.py
from django.shortcuts import render

# Create your views here.
# 특정 기능을 수행하는 view 함수들을 작성
# 모든 view 함수는 첫번째 인자로 요청 객체를 필수적으로 받는다./
def index(request):
    context = {
        'name': 'Harry',
    }
    return render(request, 'articles/index.html', context)


def dinner(request):
    foods = ['볶음밥', '보쌈', '서브웨이', '햄버거',]
    context = {
        'foods': foods,
    }
    return render(request, 'articles/dinner.html', context)


def search(request):
    return render(request, 'articles/search.html')


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    # print(request)
    # print(type(request)) # <class 'django.core.handlers.wsgi.WSGIRequest'>
    # print(dir(request))
    # print(request.GET)
    # print(request.GET.get('message'))

    data = request.GET.get('message')

    context = {
        'data': data,
    }
    return render(request, 'articles/catch.html', context)


def detail(request, num):
    context = {
        'num': num,
    }
    return render(request, 'articles/detail.html', context)


def greeting(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/greeting.html', context)

07_django/04_django_urls/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

07_django/04_django_urls/articles/templates/articles/catch.html
{% extends 'articles/base.html' %}

{% block content %}
  <h1>Catch</h1>
  <h1>{{ data }}를 받았습니다!</h1>
{% endblock content %}

07_django/04_django_urls/articles/templates/articles/detail.html
{% extends 'base.html' %}


{% block content %}
  <h1>Detail</h1>
  <h3>지금은 {{ num }}번 글입니다.</h3>
{% endblock content %}

07_django/04_django_urls/articles/templates/articles/dinner.html
{% extends 'base.html' %}

{% block content %}
  <h1>DTL 실습</h1>
  <h3>메뉴판</h3>
  <p>{{ foods }}</p>

  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>

  {% if foods|length == 0 %}
    <p>메뉴가 남아있지 않습니다.</p>
  {% else %}
    <p>메뉴가 아직 남아있습니다.</p>
  {% endif %}
{% endblock content %}

07_django/04_django_urls/articles/templates/articles/greeting.html
{% extends 'base.html' %}


{% block content %}
  <h1>Greeting</h1>
  <h3>{{ name }}님 안녕하세요!</h3>
{% endblock content %}

07_django/04_django_urls/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block style %}
  <style>
    h1 { 
      color: crimson;
    }
  </style>
{% endblock style %}

{% block content %}
  <h1>Hello, {{ name }}!!</h1>
  <a href="{% url 'articles:dinner' %}">dinner</a>
  <a href="{% url 'articles:search' %}">search</a>
  <a href="{% url 'articles:throw' %}">throw</a>
  <a href="{% url 'pages:index' %}">두번째 앱의 메인 페이지로!</a>
{% endblock content %}

07_django/04_django_urls/articles/templates/articles/search.html
{% extends 'base.html' %}

{% block content %}
  <h1>Form 실습</h1>
  <form action="https://search.naver.com/search.naver" method="GET">
    <label for="message">검색어 : </label>
    <input type="text" name="query" id="message">
    <input type="submit">
  </form>
{% endblock content %}

07_django/04_django_urls/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h1>Throw</h1>
  <form action="{% url 'articles:catch' %}" method="GET">
    <input type="text" name="message">
    <input type="submit">
  </form>
{% endblock content %}

07_django/04_django_urls/pages/templates/pages/index.html
{% extends 'base.html' %}


{% block content %}
  <h1>두번째 앱의 메인 페이지입니다.</h1>
{% endblock content %}

07_django/04_django_urls/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <title>Document</title>
  {% block style %}
  {% endblock style %}
</head>
<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>